version: "2"
services:
  flower:
    build:
      context: .
      dockerfile: Dockerfile.flower
    image: docker-registry.usersys.redhat.com/bayesian/coreapi-flower
    container_name: coreapi-flower
    network_mode: bridge
    ports:
     - "31000:5555"
    links:
     - broker
    environment:
      RABBITMQ_SERVICE_SERVICE_HOST: broker
