version: "2"
services:
  # Requires access to anitya-postgres from the main configuration
  anitya-update-job:
    image: slavek/anitya-server
    links:
      - postgres
    network_mode: bridge
    container_name: anitya-update-job
    entrypoint: /src/runupdatejob.sh
    environment:
      ANITYA_POSTGRES_SERVICE_HOST: coreapi-postgres
      ANITYA_POSTGRES_SERVICE_PORT: 5432
      POSTGRESQL_USER: coreapi
      POSTGRESQL_PASSWORD: coreapi
      POSTGRESQL_DATABASE: anitya
