# Only used by cloud-deployer
apiVersion: v1
kind: Template
metadata:
  name: secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: coreapi-postgres
  type: Opaque
  data:
    username: bayesian_db_username
    password: bayesian_db_password
    database: Y29yZWFwaQ== # coreapi
    initial-database: bayesian_db_database
    host: bayesian_db_host
    port: bayesian_db_port
- apiVersion: v1
  kind: Secret
  metadata:
    name: anitya-postgres
  type: Opaque
  data:
    username: bayesian_db_username
    password: bayesian_db_password
    database: YW5pdHlh  # anitya
    initial-database: bayesian_db_database
    host: bayesian_db_host
    port: bayesian_db_port
