apiVersion: v1
kind: Template
labels:
  template: bayesian-analytics-training
metadata:
  name: bayesian-analytics-training
  annotations:
    description: bayesian-analytics-training
objects:
- apiVersion: extensions/v1beta1
  kind: Job
  metadata:
    name: bayesian-analytics-training
  spec:
    selector:
      matchLabels:
        app: bayesian-analytics-training
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: bayesian-analytics-training
        labels:
          app: bayesian-analytics-training
      spec:
        containers:
        - command:
          - /bin/entrypoint.sh
          env:
          - name: DEPLOYMENT_PREFIX
            value: "${DEPLOYMENT_PREFIX}"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: emr-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: emr-secret-access-key
          image: registry.devshift.net/bayesian/analytics-training:latest
          name: bayesian-analytics-training
          resources:
            limits:
              memory: "512Mi"
        restartPolicy: OnFailure

parameters:
- description: Deployment prefix used for deployment-specific AWS resources
  displayName: Deployment prefix
  required: true
  name: DEPLOYMENT_PREFIX
