apiVersion: v1
kind: Template

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kompose.service.expose: "true"
    creationTimestamp: null
    labels:
      service: bayesian-anitya
    name: bayesian-anitya
  spec:
    replicas: 1
    selector:
      service: bayesian-anitya
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: bayesian-anitya
      spec:
        containers:
        - env:
          - name: ANITYA_POSTGRES_SERVICE_HOST
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: host
          - name: ANITYA_POSTGRES_SERVICE_PORT
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: port
          - name: POSTGRESQL_INITIAL_DATABASE
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: initial-database
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: database
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: password
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: username
          image: registry.devshift.net/slavek/anitya-server
          name: bayesian-anitya
          ports:
          - containerPort: 5000
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/version
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /api/projects/names
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 2
          resources:
            limits:
              memory: "512Mi"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.service.expose: "true"
    creationTimestamp: null
    labels:
      service: bayesian-anitya
    name: bayesian-anitya
  spec:
    ports:
    - name: "5000"
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      service: bayesian-anitya
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      service: bayesian-anitya-update-job
    name: bayesian-anitya-update-job
  spec:
    replicas: 1
    selector:
      service: bayesian-anitya-update-job
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: bayesian-anitya-update-job
      spec:
        containers:
        - env:
          - name: ANITYA_POSTGRES_SERVICE_HOST
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: host
          - name: ANITYA_POSTGRES_SERVICE_PORT
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: port
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: database
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: password
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: username
          image: slavek/anitya-server
          name: bayesian-anitya-update-job
          command:
            - /src/runupdatejob.sh
          resources:
            limits:
              memory: "512Mi"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
