apiVersion: v1
kind: Template
labels:
  template: bayesian-data-model-importer
metadata:
  name: bayesian-data-model-importer
  annotations:
    description: bayesian-data-model-importer
objects:
- apiVersion: extensions/v1beta1
  kind: Job
  metadata:
    name: bayesian-data-model-importer
  spec:
    template:
      metadata:
        name: bayesian-data-model-importer
        labels:
          service: bayesian-data-model-importer
      spec:
        containers:
        - env:
          - name: AWS_BUCKET
            value: "${S3_BUCKET_FOR_ANALYSES}"
          - name: AWS_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: s3-secret-access-key
          - name: AWS_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: s3-access-key-id
          image: ${IMPORTER_IMAGE}
          name: bayesian-data-model-importer
          resources:
            limits:
              memory: "1024Mi"
        restartPolicy: OnFailure

parameters:
- description: Name of the S3 bucket where to store analyses
  displayName: S3 bucket for analyses
  required: True
  name: S3_BUCKET_FOR_ANALYSES
- description: IMPORTER_IMAGE
  required: True
  name: IMPORTER_IMAGE
  value: registry.devshift.net/bayesian/data-model-importer:latest
- description: Use secure connection for Gremlin queries
  required: False
  name: GREMLIN_USE_SECURE_CONNECTION
  value: "false"
