apiVersion: v1
kind: Template
labels:
  template: bayesian-postgresql
metadata:
  name: bayesian-postgresql
  annotations:
    description: Bayesian PostgreSQL
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      service: bayesian-postgres
    name: bayesian-postgres
  spec:
    replicas: 1
    selector:
      service: bayesian-postgres
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: bayesian-postgres
      spec:
        containers:
        - env:
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: database
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: password
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: username
          image: registry.centos.org/sclo/postgresql-94-centos7:latest
          name: bayesian-postgres
          ports:
          - containerPort: 5432
            protocol: TCP
          resources:
            limits:
              memory: "512Mi"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: bayesian-postgres
    name: bayesian-postgres
  spec:
    ports:
    - name: "5432"
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      service: bayesian-postgres
  status:
    loadBalancer: {}
