apiVersion: v1
kind: Template
labels:
  template: bayesian-postgresql-extras
metadata:
  name: bayesian-postgresql-extras
  annotations:
    description: Bayesian PostgreSQL-related jobs and services
objects:
- apiVersion: extensions/v1beta1
  kind: Job
  metadata:
    creationTimestamp: null
    labels:
      service: bayesian-downstream-data-import
    name: bayesian-downstream-data-import
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: bayesian-downstream-data-import
        labels:
          service: bayesian-downstream-data-import
      spec:
        containers:
        - env:
          - name: PGBOUNCER_SERVICE_HOST
            value: bayesian-pgbouncer
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: database
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: password
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: username
          image: registry.devshift.net/bayesian/coreapi-downstream-data-import
          name: bayesian-downstream-data-import
          resources:
            limits:
              memory: "512Mi"
        restartPolicy: OnFailure

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      service: bayesian-pgbouncer
    name: bayesian-pgbouncer
  spec:
    replicas: 1
    selector:
      service: bayesian-pgbouncer
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: bayesian-pgbouncer
      spec:
        containers:
        - env:
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: database
          - name: POSTGRESQL_INITIAL_DATABASE
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: initial-database
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: password
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: username
          - name: POSTGRES_SERVICE_HOST
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: host
          - name: POSTGRES_SERVICE_PORT
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: port
          image: registry.devshift.net/bayesian/coreapi-pgbouncer
          name: bayesian-pgbouncer
          livenessProbe:
            exec:
              command: ["health-check-probe.sh"]
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 2
          ports:
          - containerPort: 5432
            protocol: TCP
          resources:
            limits:
              memory: "256Mi"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: bayesian-pgbouncer
    name: bayesian-pgbouncer
  spec:
    ports:
    - name: "5432"
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      service: bayesian-pgbouncer
  status:
    loadBalancer: {}
